spring.application.name=market

# Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://mysql-db:3306/market_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=market_user
spring.datasource.password=market_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=false
spring.flyway.baseline-version=1


logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Puerto de la aplicacion
server.port=8080

# JWT settings
security.jwt.secret=${JWT_SECRET:change-me}
security.jwt.access-expiration-minutes=15
security.jwt.refresh-expiration-days=14
security.jwt.issuer=market-api


# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=products-group
spring.kafka.consumer.properties.spring.json.trusted.packages=*


# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# Spring Batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

google.oauth.client-id=TU_CLIENT_ID.apps.googleusercontent.com
google.oauth.client-secret=TU_CLIENT_SECRET
google.oauth.redirect-uri=http://localhost:8080/api/auth/google/callback